stages:
  - build

development:
  stage: build
  script: 
  - "mkdir Build"
  - "mkdir Artifacts"
  - "cd Artifacts"
  - "mkdir Missions"
  - "cd .."
  - "python ./compile.py"
  environment:
    name: development
  artifacts:
    name: "%CI_JOB_NAME-%CI_COMMIT_REF_NAME"
    paths:
    - Artifacts/Missions
    - Artifacts/Addons
