stages:
  - build
  - deploy

compile:
  stage: build
  script: 
  - "mkdir Build"
  - "mkdir Packed"
  - "cd Packed"
  - "mkdir Missions"
  - "cd .."
  - "python ./compile.py"

development:
  stage: deploy
  script: "echo Deploying development build..."
  artifacts:
    name: "co10_Escape-%CI_COMMIT_REF_SLUG-%CI_COMMIT_SHA"
    paths:
    - Packed/Missions
    - Packed/Addons
  except:
    - tags
  
release:
  stage: deploy
  script: "echo Deploying %CI_COMMIT_TAG tag..."
  artifacts:
    name: "co10_Escape-%CI_COMMIT_TAG"
    paths:
    - Packed/Missions
    - Packed/Addons
  only:
    - tags

