stages:
  - build

job 1:
  stage: build
  script: 
  - "mkdir ./Build"
  - "python ./compile.py"
  environment:
    name: development
  artifacts:
    name: "%CI_JOB_NAME-%CI_COMMIT_REF_NAME"
    paths:
    - Build/missionfiles
    - Build/addons
